name       : ace
version    : 1.1
release    : 2
source     :
    - http://pilotfiber.dl.sourceforge.net/project/ucsniff/ace/ace-1.10.tar.gz : d5b4c5ef2b4537b8f6cb4ab98d0bfd6f34392477aafb0f492fd833f4f55aca49
license    : GPL-2.0
component  : security
summary    : a simple yet powerful VoIP Corporate Directory enumeration tool that
    mimics the behavior of an IP Phone
description: |
    a simple yet powerful VoIP Corporate Directory enumeration tool that mimics the behavior of an IP Phone
builddeps  :
    - libpcap-devel
setup      : |
    sed -i "s|<linux/if_tr.h>|<netinet/if_tr.h>|" client.h
build      : |
    %make
install    : |
    install -D -m00755 ace $installdir/usr/bin/ace
