name       : ace
version    : '1.10'
release    : 5
source     :
    - https://sourceforge.net/projects/ucsniff/files/ace/ace-1.10.tar.gz/download : d5b4c5ef2b4537b8f6cb4ab98d0bfd6f34392477aafb0f492fd833f4f55aca49
homepage   : http://ucsniff.sourceforge.net/ace.html
license    : GPL-2.0-or-later
component  : security
summary    : ACE VoIP Corporate Directory enumeration tool
description: |
    ACE (Automated Corporate Enumerator) is a simple yet powerful VoIP Corporate Directory enumeration tool that mimics the behavior of an IP Phone in order to download the name and extension entries that a given phone can display on its screen interface.
builddeps  :
    - pkgconfig(libpcap)
    - pkgconfig(libtirpc)
environment:
    export CFLAGS="${CFLAGS} -fcommon -I/usr/include/tirpc"
setup      : |
    sed -i "s|<linux/if_tr.h>|<netinet/if_tr.h>|" client.h
    sed -i "s:gcc :gcc $CFLAGS :g" Makefile
build      : |
    %make
install    : |
    install -Dm00755 ace $installdir/usr/bin/ace
